export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const GET_ALL_CANDIDATE = "GET_ALL_CANDIDATE";
export const GET_CANDIDATE = "GET_CANDIDATE";
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const DELETE_CANDIDATE = "DELETE_CANDIDATE";
export const SELECT_CANDIDATE = "SELECT_CANDIDATE";
export const CLEAR_CANDIDATE = "CLEAR_CANDIDATE";
export const DELETE_SELECTED_CANDIDATE = "DELETE_SELECTED_CANDIDATE";
